<?php

/**
 * @file
 * Primary module hooks for CUA IR20 Content Types module.
 *
 * @DCG
 * This file is no longer required in Drupal 8.
 * @see https://www.drupal.org/node/2217931
 */

use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_form_FORM_ID_alter().
 */
function cua_ir20_content_types_form_alter(&$form, FormStateInterface $form_state, $form_id) {

  switch ($form_id) {
    case 'block_content_content_list_form':
      $form["visibility"]["node_type"]["bundles"]["#options"] = [
        'story' => 'Story',
      ];
      $form['actions']['submit']['#submit'][] = 'cua_ir20_save_content_list';
      break;

    case 'block_content_image_form':
      $form['actions']['submit']['#submit'][] = 'cua_ir20_save_image_block';
      break;

    case 'block_content_text_form':
      $form['actions']['submit']['#submit'][] = 'cua_ir20_save_text_block';
      break;
  }
}

/**
 * Saves the content list.
 */
function cua_ir20_save_content_list(&$form, FormStateInterface $form_state) {
  // $foo = 'bar';
}

/**
 * Implements hook_plugin_filter_TYPE__CONSUMER_alter().
 */
function cua_ir20_content_types_plugin_filter_block__layout_builder_alter(array &$definitions, array $extra) {
  // @todo Make this into a variable editable by UI.
  // Exclude everything but custom blocks for now.
  $retain_id_list = ['block_content', 'inline_block'];

  // Curate the blocks available in the Layout Builder "Add Block" UI.
  $new_definitions = $definitions;
  foreach ($new_definitions as $key => $definition) {
    if (!in_array($definition['id'], $retain_id_list, TRUE)) {
      unset($definitions[$key]);
    }
  }
}
